//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.salesorders = new HashSet<salesorder>();
            this.salesreceipts = new HashSet<salesreceipt>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Tel { get; set; }
    
        public virtual ICollection<salesorder> salesorders { get; set; }
        public virtual ICollection<salesreceipt> salesreceipts { get; set; }
    }
}
