//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class goodsreceivednote
    {
        public int ReceivedID { get; set; }
        public int PurchaseOrderID { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime InboundDate { get; set; }
        public System.TimeSpan InboundTime { get; set; }
    
        public virtual purchaseorder purchaseorder { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
