//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class goodreturnnote_item
    {
        public int ReturnNoteID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual goodreturnnote goodreturnnote { get; set; }
        public virtual item item { get; set; }
    }
}
