//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class reorderrequest_item
    {
        public int ItemID { get; set; }
        public int ReorderRequestID { get; set; }
        public int Qty { get; set; }
    
        public virtual reorderrequest reorderrequest { get; set; }
    }
}
