//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesorder_item
    {
        public int SalesOrderID { get; set; }
        public int ItemID { get; set; }
        public int SalePrice { get; set; }
        public int Qty { get; set; }
        public Nullable<int> WarrantyMouth { get; set; }
        public string SerialNo { get; set; }
    
        public virtual item item { get; set; }
        public virtual salesorder salesorder { get; set; }
    }
}
