//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Incorrect user name or password, please try again.")]
        public string LoginMsgBoxEn {
            get {
                return ((string)(this["LoginMsgBoxEn"]));
            }
            set {
                this["LoginMsgBoxEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("用户名或密码错误，请再试一次。")]
        public string LoginMsgBoxZh {
            get {
                return ((string)(this["LoginMsgBoxZh"]));
            }
            set {
                this["LoginMsgBoxZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Staff ID should be numeric")]
        public string lblStaffIDWarningEn {
            get {
                return ((string)(this["lblStaffIDWarningEn"]));
            }
            set {
                this["lblStaffIDWarningEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("员工编号应为数字")]
        public string lblStaffIDWarningZh {
            get {
                return ((string)(this["lblStaffIDWarningZh"]));
            }
            set {
                this["lblStaffIDWarningZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Staff ID is required.")]
        public string errorMessageRequiredEn {
            get {
                return ((string)(this["errorMessageRequiredEn"]));
            }
            set {
                this["errorMessageRequiredEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入员工编号。")]
        public string errorMessageRequiredZh {
            get {
                return ((string)(this["errorMessageRequiredZh"]));
            }
            set {
                this["errorMessageRequiredZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Staff ID must be 5 digit.")]
        public string errorMessageFiveEn {
            get {
                return ((string)(this["errorMessageFiveEn"]));
            }
            set {
                this["errorMessageFiveEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("员工编号必须是 5 位数字。")]
        public string errorMessageFiveZh {
            get {
                return ((string)(this["errorMessageFiveZh"]));
            }
            set {
                this["errorMessageFiveZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Username is required.")]
        public string errorMessageUsernameEn {
            get {
                return ((string)(this["errorMessageUsernameEn"]));
            }
            set {
                this["errorMessageUsernameEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入用户名。")]
        public string errorMessageUsernameZh {
            get {
                return ((string)(this["errorMessageUsernameZh"]));
            }
            set {
                this["errorMessageUsernameZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usernames must be between 4 and 20 characters.")]
        public string errorMessageUsernameValidEn {
            get {
                return ((string)(this["errorMessageUsernameValidEn"]));
            }
            set {
                this["errorMessageUsernameValidEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("用户名必须介于 4 到 20 个字符之间。")]
        public string errorMessageUsernameValidZh {
            get {
                return ((string)(this["errorMessageUsernameValidZh"]));
            }
            set {
                this["errorMessageUsernameValidZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please check your password strength.")]
        public string errorMessagePasswordEn {
            get {
                return ((string)(this["errorMessagePasswordEn"]));
            }
            set {
                this["errorMessagePasswordEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请检查您的密码强度。")]
        public string errorMessagePasswordZh {
            get {
                return ((string)(this["errorMessagePasswordZh"]));
            }
            set {
                this["errorMessagePasswordZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password is required.")]
        public string errorMessagePasswordRequiredEn {
            get {
                return ((string)(this["errorMessagePasswordRequiredEn"]));
            }
            set {
                this["errorMessagePasswordRequiredEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入密码。")]
        public string errorMessagePasswordRequiredZh {
            get {
                return ((string)(this["errorMessagePasswordRequiredZh"]));
            }
            set {
                this["errorMessagePasswordRequiredZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password must be at least 8 characters long.")]
        public string errorMessagePasswordValidEn {
            get {
                return ((string)(this["errorMessagePasswordValidEn"]));
            }
            set {
                this["errorMessagePasswordValidEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("密码长度必须至少为 8 个字符。")]
        public string errorMessagePasswordValidZh {
            get {
                return ((string)(this["errorMessagePasswordValidZh"]));
            }
            set {
                this["errorMessagePasswordValidZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Confirm password is required.")]
        public string errorMessagePasswordConfirmEn {
            get {
                return ((string)(this["errorMessagePasswordConfirmEn"]));
            }
            set {
                this["errorMessagePasswordConfirmEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入确认密码。")]
        public string errorMessagePasswordConfirmZh {
            get {
                return ((string)(this["errorMessagePasswordConfirmZh"]));
            }
            set {
                this["errorMessagePasswordConfirmZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Passwords do not match. Please try again.")]
        public string errorMessagePasswordMatchEn {
            get {
                return ((string)(this["errorMessagePasswordMatchEn"]));
            }
            set {
                this["errorMessagePasswordMatchEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("密码不匹配。请再试一次。")]
        public string errorMessagePasswordMatchZh {
            get {
                return ((string)(this["errorMessagePasswordMatchZh"]));
            }
            set {
                this["errorMessagePasswordMatchZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Email address is required.")]
        public string errorMessageEmailEn {
            get {
                return ((string)(this["errorMessageEmailEn"]));
            }
            set {
                this["errorMessageEmailEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入电子邮件地址。")]
        public string errorMessageEmailZh {
            get {
                return ((string)(this["errorMessageEmailZh"]));
            }
            set {
                this["errorMessageEmailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sign up failed. Please sign up again.")]
        public string SignupMsgBoxFailEn {
            get {
                return ((string)(this["SignupMsgBoxFailEn"]));
            }
            set {
                this["SignupMsgBoxFailEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("注册失败。请重新注册。")]
        public string SignupMsgBoxFailZh {
            get {
                return ((string)(this["SignupMsgBoxFailZh"]));
            }
            set {
                this["SignupMsgBoxFailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sign up failed. Incorrect staff ID.")]
        public string SignupMsgBoxStaffIDFailEn {
            get {
                return ((string)(this["SignupMsgBoxStaffIDFailEn"]));
            }
            set {
                this["SignupMsgBoxStaffIDFailEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("注册失败。员工编号不正确。")]
        public string SignupMsgBoxStaffIDFailZh {
            get {
                return ((string)(this["SignupMsgBoxStaffIDFailZh"]));
            }
            set {
                this["SignupMsgBoxStaffIDFailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sign up failed. Username already exists.")]
        public string SignupMsgBoxUsernameFailEn {
            get {
                return ((string)(this["SignupMsgBoxUsernameFailEn"]));
            }
            set {
                this["SignupMsgBoxUsernameFailEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sign up successfully, please check your email.")]
        public string SignupMsgBoxEmailEn {
            get {
                return ((string)(this["SignupMsgBoxEmailEn"]));
            }
            set {
                this["SignupMsgBoxEmailEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("注册成功，请查电子收邮箱。")]
        public string SignupMsgBoxEmailZh {
            get {
                return ((string)(this["SignupMsgBoxEmailZh"]));
            }
            set {
                this["SignupMsgBoxEmailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("欢迎")]
        public string SignupMsgBoxEmailTitleZh {
            get {
                return ((string)(this["SignupMsgBoxEmailTitleZh"]));
            }
            set {
                this["SignupMsgBoxEmailTitleZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("应填写所有信息。")]
        public string CreateStaffFormMsgBoxFillZh {
            get {
                return ((string)(this["CreateStaffFormMsgBoxFillZh"]));
            }
            set {
                this["CreateStaffFormMsgBoxFillZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("成功创建员工。")]
        public string CreateStaffFormMsgBoxSucZh {
            get {
                return ((string)(this["CreateStaffFormMsgBoxSucZh"]));
            }
            set {
                this["CreateStaffFormMsgBoxSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("创建员工失败。")]
        public string CreateStaffFormMsgBoxUnucZh {
            get {
                return ((string)(this["CreateStaffFormMsgBoxUnucZh"]));
            }
            set {
                this["CreateStaffFormMsgBoxUnucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("成功更新员工资料。")]
        public string EditStaffUpdateZh {
            get {
                return ((string)(this["EditStaffUpdateZh"]));
            }
            set {
                this["EditStaffUpdateZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更新员工资料失败。")]
        public string EditStaffUpdateFailZh {
            get {
                return ((string)(this["EditStaffUpdateFailZh"]));
            }
            set {
                this["EditStaffUpdateFailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("删除成功。")]
        public string ViewStaffDeleteZh {
            get {
                return ((string)(this["ViewStaffDeleteZh"]));
            }
            set {
                this["ViewStaffDeleteZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("删除失败。")]
        public string ViewStaffDeleteFailZh {
            get {
                return ((string)(this["ViewStaffDeleteFailZh"]));
            }
            set {
                this["ViewStaffDeleteFailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("成功更新帐户资料。")]
        public string UpdateUserZh {
            get {
                return ((string)(this["UpdateUserZh"]));
            }
            set {
                this["UpdateUserZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更新帐户资料失败。")]
        public string UpdateUserFailZh {
            get {
                return ((string)(this["UpdateUserFailZh"]));
            }
            set {
                this["UpdateUserFailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("该项目已被选取。")]
        public string DeliveryWorkerZh {
            get {
                return ((string)(this["DeliveryWorkerZh"]));
            }
            set {
                this["DeliveryWorkerZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("已选择此交货单。")]
        public string DeliveryWorkerDeZh {
            get {
                return ((string)(this["DeliveryWorkerDeZh"]));
            }
            set {
                this["DeliveryWorkerDeZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请选择工人。")]
        public string SelectWorkmanZh {
            get {
                return ((string)(this["SelectWorkmanZh"]));
            }
            set {
                this["SelectWorkmanZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请选择交货单到安排清单。")]
        public string SelectDOZh {
            get {
                return ((string)(this["SelectDOZh"]));
            }
            set {
                this["SelectDOZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("安排成功。")]
        public string ArrangeSucZh {
            get {
                return ((string)(this["ArrangeSucZh"]));
            }
            set {
                this["ArrangeSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("安排不成功。")]
        public string ArrangeUnsucZh {
            get {
                return ((string)(this["ArrangeUnsucZh"]));
            }
            set {
                this["ArrangeUnsucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更新成功。")]
        public string UpdateSucZh {
            get {
                return ((string)(this["UpdateSucZh"]));
            }
            set {
                this["UpdateSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更新失败。")]
        public string UpdateUnsucZh {
            get {
                return ((string)(this["UpdateUnsucZh"]));
            }
            set {
                this["UpdateUnsucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请选择您要更新的记录")]
        public string SelectUpdateZh {
            get {
                return ((string)(this["SelectUpdateZh"]));
            }
            set {
                this["SelectUpdateZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" 没收到。请与供应商联系。")]
        public string NotRecSupplierZh {
            get {
                return ((string)(this["NotRecSupplierZh"]));
            }
            set {
                this["NotRecSupplierZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("点击下面的收货说明以显示详细信息。")]
        public string ClickRecDetailsZh {
            get {
                return ((string)(this["ClickRecDetailsZh"]));
            }
            set {
                this["ClickRecDetailsZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请选择安装单到安排清单。")]
        public string SelectIOZh {
            get {
                return ((string)(this["SelectIOZh"]));
            }
            set {
                this["SelectIOZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("添加成功。")]
        public string AddSucZh {
            get {
                return ((string)(this["AddSucZh"]));
            }
            set {
                this["AddSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("添加失败。")]
        public string AddUnsucZh {
            get {
                return ((string)(this["AddUnsucZh"]));
            }
            set {
                this["AddUnsucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入数字。")]
        public string label_SalesPriceZh {
            get {
                return ((string)(this["label_SalesPriceZh"]));
            }
            set {
                this["label_SalesPriceZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请选择供应商编号")]
        public string SelectSupIDZh {
            get {
                return ((string)(this["SelectSupIDZh"]));
            }
            set {
                this["SelectSupIDZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请选择是否允许送货")]
        public string SelectDelZh {
            get {
                return ((string)(this["SelectDelZh"]));
            }
            set {
                this["SelectDelZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入商品名称")]
        public string ItemNameZh {
            get {
                return ((string)(this["ItemNameZh"]));
            }
            set {
                this["ItemNameZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入类别")]
        public string CategoryZh {
            get {
                return ((string)(this["CategoryZh"]));
            }
            set {
                this["CategoryZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入描述")]
        public string DescZh {
            get {
                return ((string)(this["DescZh"]));
            }
            set {
                this["DescZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入销售价格")]
        public string SaleZh {
            get {
                return ((string)(this["SaleZh"]));
            }
            set {
                this["SaleZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入供应商价格")]
        public string SupZh {
            get {
                return ((string)(this["SupZh"]));
            }
            set {
                this["SupZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入保修月份")]
        public string WarZh {
            get {
                return ((string)(this["WarZh"]));
            }
            set {
                this["WarZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("无效保修月份")]
        public string InvalidWMZh {
            get {
                return ((string)(this["InvalidWMZh"]));
            }
            set {
                this["InvalidWMZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入有效保修月份")]
        public string ValidWMZh {
            get {
                return ((string)(this["ValidWMZh"]));
            }
            set {
                this["ValidWMZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未插入项目。")]
        public string ItemNZh {
            get {
                return ((string)(this["ItemNZh"]));
            }
            set {
                this["ItemNZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未添加任何货品。")]
        public string NoItemZh {
            get {
                return ((string)(this["NoItemZh"]));
            }
            set {
                this["NoItemZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入付款金额。")]
        public string AmountZh {
            get {
                return ((string)(this["AmountZh"]));
            }
            set {
                this["AmountZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入足够的付款金额。")]
        public string SAmountZh {
            get {
                return ((string)(this["SAmountZh"]));
            }
            set {
                this["SAmountZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("购买不成功。")]
        public string PurchaseUnZh {
            get {
                return ((string)(this["PurchaseUnZh"]));
            }
            set {
                this["PurchaseUnZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("采购订单成功。")]
        public string POSucZh {
            get {
                return ((string)(this["POSucZh"]));
            }
            set {
                this["POSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("重新订购失败。")]
        public string ReorderUnsZh {
            get {
                return ((string)(this["ReorderUnsZh"]));
            }
            set {
                this["ReorderUnsZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请选择货品。")]
        public string SelectItemZh {
            get {
                return ((string)(this["SelectItemZh"]));
            }
            set {
                this["SelectItemZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请单击待处理的重新订购请求。")]
        public string ClickReorderZh {
            get {
                return ((string)(this["ClickReorderZh"]));
            }
            set {
                this["ClickReorderZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("单击下面的重新订购请求以显示详细信息。")]
        public string ClickRoDetailsZh {
            get {
                return ((string)(this["ClickRoDetailsZh"]));
            }
            set {
                this["ClickRoDetailsZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("此货品已被选中。")]
        public string AlreadyZh {
            get {
                return ((string)(this["AlreadyZh"]));
            }
            set {
                this["AlreadyZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("此商品数量不能小于 1。")]
        public string SmallThanOneZh {
            get {
                return ((string)(this["SmallThanOneZh"]));
            }
            set {
                this["SmallThanOneZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量不能为空。")]
        public string QtyNullZh {
            get {
                return ((string)(this["QtyNullZh"]));
            }
            set {
                this["QtyNullZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("提交成功。")]
        public string SubSucZh {
            get {
                return ((string)(this["SubSucZh"]));
            }
            set {
                this["SubSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("荃湾")]
        public string TWZh {
            get {
                return ((string)(this["TWZh"]));
            }
            set {
                this["TWZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("九龙湾")]
        public string KLBZh {
            get {
                return ((string)(this["KLBZh"]));
            }
            set {
                this["KLBZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("此订单的商品数量不多。")]
        public string ItmQtyZh {
            get {
                return ((string)(this["ItmQtyZh"]));
            }
            set {
                this["ItmQtyZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("退货金额：$")]
        public string ReturnAmtZh {
            get {
                return ((string)(this["ReturnAmtZh"]));
            }
            set {
                this["ReturnAmtZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("您在退货单中有物品。")]
        public string ReturnHvZh {
            get {
                return ((string)(this["ReturnHvZh"]));
            }
            set {
                this["ReturnHvZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("您还没有选择要放置退货单的商店。")]
        public string ReturnNoSelZh {
            get {
                return ((string)(this["ReturnNoSelZh"]));
            }
            set {
                this["ReturnNoSelZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入供应商名称")]
        public string SupNameZh {
            get {
                return ((string)(this["SupNameZh"]));
            }
            set {
                this["SupNameZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入地址")]
        public string AddZh {
            get {
                return ((string)(this["AddZh"]));
            }
            set {
                this["AddZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入正确的电话号码")]
        public string TelZh {
            get {
                return ((string)(this["TelZh"]));
            }
            set {
                this["TelZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please enter a valid email address.\nFor example abc@def.com")]
        public string errorMessageEmailValidEn {
            get {
                return ((string)(this["errorMessageEmailValidEn"]));
            }
            set {
                this["errorMessageEmailValidEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请输入有效的电子邮件地址。\n例如 abc@def.com")]
        public string errorMessageEmailValidZh {
            get {
                return ((string)(this["errorMessageEmailValidZh"]));
            }
            set {
                this["errorMessageEmailValidZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("注册失败。此用户名已存在。")]
        public string SignupMsgBoxUsernameFailZh {
            get {
                return ((string)(this["SignupMsgBoxUsernameFailZh"]));
            }
            set {
                this["SignupMsgBoxUsernameFailZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("收货单创建成功。\n单号： ")]
        public string RecCreateSucZh {
            get {
                return ((string)(this["RecCreateSucZh"]));
            }
            set {
                this["RecCreateSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("应填写所有信息\n项目图片除外）")]
        public string MsgBoxFillZh {
            get {
                return ((string)(this["MsgBoxFillZh"]));
            }
            set {
                this["MsgBoxFillZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("重新订购请求成功。\n重新订购请求编号：")]
        public string ReorderSucZh {
            get {
                return ((string)(this["ReorderSucZh"]));
            }
            set {
                this["ReorderSucZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("低级数量应该是数字。")]
        public string LowLevelQtyZh {
            get {
                return ((string)(this["LowLevelQtyZh"]));
            }
            set {
                this["LowLevelQtyZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("在退货单中放置商品时，您不能选择其他销售订单。\n请清除退货说明，然后重试。")]
        public string ReturnCSZh {
            get {
                return ((string)(this["ReturnCSZh"]));
            }
            set {
                this["ReturnCSZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("语言")]
        public string LanZh {
            get {
                return ((string)(this["LanZh"]));
            }
            set {
                this["LanZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("月份")]
        public string MonthZh {
            get {
                return ((string)(this["MonthZh"]));
            }
            set {
                this["MonthZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("销售订单数量")]
        public string SocZh {
            get {
                return ((string)(this["SocZh"]));
            }
            set {
                this["SocZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("销售")]
        public string SalesZh {
            get {
                return ((string)(this["SalesZh"]));
            }
            set {
                this["SalesZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("行政")]
        public string AdminZh {
            get {
                return ((string)(this["AdminZh"]));
            }
            set {
                this["AdminZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("首席执行官")]
        public string CEOZh {
            get {
                return ((string)(this["CEOZh"]));
            }
            set {
                this["CEOZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("会计部")]
        public string AccountZh {
            get {
                return ((string)(this["AccountZh"]));
            }
            set {
                this["AccountZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("存货部")]
        public string InventoryZh {
            get {
                return ((string)(this["InventoryZh"]));
            }
            set {
                this["InventoryZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("采购部")]
        public string PurchaseZh {
            get {
                return ((string)(this["PurchaseZh"]));
            }
            set {
                this["PurchaseZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("销售部")]
        public string SalesDZh {
            get {
                return ((string)(this["SalesDZh"]));
            }
            set {
                this["SalesDZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("会计经理")]
        public string AMZh {
            get {
                return ((string)(this["AMZh"]));
            }
            set {
                this["AMZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("会计文员")]
        public string ACZh {
            get {
                return ((string)(this["ACZh"]));
            }
            set {
                this["ACZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("库存经理")]
        public string IMZh {
            get {
                return ((string)(this["IMZh"]));
            }
            set {
                this["IMZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("库存文员")]
        public string ICZh {
            get {
                return ((string)(this["ICZh"]));
            }
            set {
                this["ICZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("进货文员")]
        public string GICZh {
            get {
                return ((string)(this["GICZh"]));
            }
            set {
                this["GICZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("送货员")]
        public string DelZh {
            get {
                return ((string)(this["DelZh"]));
            }
            set {
                this["DelZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("采购经理")]
        public string PMZh {
            get {
                return ((string)(this["PMZh"]));
            }
            set {
                this["PMZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("采购员")]
        public string POZh {
            get {
                return ((string)(this["POZh"]));
            }
            set {
                this["POZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("销售员")]
        public string SRZh {
            get {
                return ((string)(this["SRZh"]));
            }
            set {
                this["SRZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("销售經理")]
        public string SMZh {
            get {
                return ((string)(this["SMZh"]));
            }
            set {
                this["SMZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("技术支援部")]
        public string TSZh {
            get {
                return ((string)(this["TSZh"]));
            }
            set {
                this["TSZh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("细节")]
        public string DetailsZh {
            get {
                return ((string)(this["DetailsZh"]));
            }
            set {
                this["DetailsZh"] = value;
            }
        }
    }
}
